# Note: Smaller area and height values result in less lag.
# baseBlockSpeeds speed less than 0.4 may not work well.
# autoPlace will automatically move players to be fully in the elevator
# preventEntry will prevent players from entering an active elevator (at the cost of possible lag when lifts are running)
# soundVolume (0-100) defines the relative volume for all sounds.
maxLiftArea: 16
maxHeight: 256
minHeight: 0
debug: false
autoPlace: false
preventEntry: false
preventLeave: true
liftMobs: true
mouseScroll: true
secondsUntilTimeout: 2
floorBlocks:
  - GLASS
  - "*_STAINED_GLASS"
buttonBlocks:
  - "*BUTTON"
signBlocks:
  - "*WALL_SIGN"
shaftBlocks:
  - LADDER
  - SNOW
  - TORCH
  - VINE
  - WATER
  - "*RAIL"
  - REDSTONE_WIRE
baseBlocks:
  IRON_BLOCK:
    speed: 0.5
  NOTE_BLOCK:
    speed: 0.2
    music: true
soundEnabled: true
soundVolume: 100
messages:
  destination: "&7Destination"
  currentFloor: "&7Current Floor"
  cantEnter: "&7Can't enter elevator in use"
  cantLeave: "&7Can't leave elevator in use"
  oneFloor: "&7There is only one floor."
  unsafe: "&cIt is unsafe to leave a vehicle in a lift!"
  floorNotExists: "&cFloor does not exist. Check shaft for blockage"
  scrollSelectEnabled: "&7Scrollable floor selection enabled. Click on sign with an item for default mode"
  scrollSelectDisabled: "&7Scrollable floor selection disabled"
  timeout: "&7You have been teleported to destination due to timeout"
